export enum CacheTag {
  Address = 'address',
  CollegeProfile = 'collegeProfile',
  ListAddonCourse = 'listAddonCourse',
  ListBooks = 'listBooks',
  ListFeesTypes = 'listFeesTypes',
  ListLanguages = 'listLanguages',
  ListPrograms = 'listPrograms',
  ListProgramAddon = 'listProgramAddon',
  ListProgramBooks = 'listProgramBooks',
  ListProgramSegments = 'listProgramSegments',
  ListProgramSecondLanguages = 'listProgramSecondLanguages',
  ListProgramMediums = 'listProgramMediums',
  ListProgramSections = 'listProgramSections',
  ListUsers = 'listUsers',
  ProgramFees = 'programFees',
  StudentPayment = 'studentPayment',
  StudentAddress = 'studentAddress',
  User = 'user',
  UserPermissions = 'userPermissions',
  Section = 'section'
}
