version: 2.1

jobs:
  test_and_sonar:
    docker:
      - image: cimg/node:20.10

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: Run Jest Tests with Coverage
          command: |
            npm run test -- --coverage

      - run:
          name: Install Sonar Scanner
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip wget
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner-cli-5.0.1.3006-linux.zip
            echo 'export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.organization=rajasekharm81 \
            -Dsonar.projectKey=rajasekharm81_chaarvy_fe_v2 \
            -Dsonar.pullrequest.key=$CIRCLE_PR_NUMBER \
            -Dsonar.pullrequest.branch=$CIRCLE_BRANCH \
            -Dsonar.pullrequest.base=main

workflows:
  version: 2

  test_and_analyze:
    jobs:
      - test_and_sonar
