version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:24.0
    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
            - node-cache-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Run ESLint (fail if any issue)
          command: npm run lint

      - run:
          name: Run Jest tests with coverage
          command: npm run test -- --coverage

  deploy:
    docker:
      - image: cimg/node:24.0

    steps:
      - run:
          name: Trigger Netlify Build
          command: |
            curl -X POST $https://api.netlify.com/build_hooks/69cf2e17b890b79911794909

workflows:
  version: 2
  ci_cd_pipeline:
    jobs:
      - test
      - deploy:
          requires:
            - test
