export enum ChaarvyIcon {
  Abacus = 'Abacus',
  Account = 'Account',
  AbTesting = 'AbTesting',
  AccountBox = 'AccountBox',
  AccountCog = 'AccountCog',
  AbjadArabic = 'AbjadArabic',
  AbjadHebrew = 'AbjadHebrew',
  AbugidaThai = 'AbugidaThai',
  AccessPoint = 'AccessPoint',
  AccountCash = 'AccountCash',
  AccountEdit = 'AccountEdit',
  AccountAlert = 'AccountAlert',
  AccountCheck = 'AccountCheck',
  AccountChild = 'AccountChild',
  AccountClock = 'AccountClock',
  AccountGroup = 'AccountGroup',
  AccountCancel = 'AccountCancel',
  AccountCircle = 'AccountCircle',
  AccessPointOff = 'AccessPointOff',
  AccountConvert = 'AccountConvert',
  AccountDetails = 'AccountDetails',
  AccessPointPlus = 'AccessPointPlus',
  AccessPointCheck = 'AccessPointCheck',
  AccessPointMinus = 'AccessPointMinus',
  AccountArrowLeft = 'AccountArrowLeft',
  AccountCowboyHat = 'AccountCowboyHat',
  AbugidaDevanagari = 'AbugidaDevanagari',
  AccessPointRemove = 'AccessPointRemove',
  AccountArrowRight = 'AccountArrowRight',
  AccountBoxOutline = 'AccountBoxOutline',
  AccountCogOutline = 'AccountCogOutline',
  AccessPointNetwork = 'AccessPointNetwork',
  AccountBoxMultiple = 'AccountBoxMultiple',
  AccountCashOutline = 'AccountCashOutline',
  AccountChildCircle = 'AccountChildCircle',
  AccountEditOutline = 'AccountEditOutline',
  AccountAlertOutline = 'AccountAlertOutline',
  AccountCheckOutline = 'AccountCheckOutline',
  AccountChildOutline = 'AccountChildOutline',
  AccountClockOutline = 'AccountClockOutline',
  AccountCancelOutline = 'AccountCancelOutline',
  AccountCircleOutline = 'AccountCircleOutline',
  AccessPointNetworkOff = 'AccessPointNetworkOff',
  AccountConvertOutline = 'AccountConvertOutline',
  AccountDetailsOutline = 'AccountDetailsOutline',
  AccountArrowLeftOutline = 'AccountArrowLeftOutline',
  AccountArrowRightOutline = 'AccountArrowRightOutline',
  AccountBoxMultipleOutline = 'AccountBoxMultipleOutline',
  TrendingUp = 'TrendingUp',
  CurrencyUsd = 'CurrencyUsd',
  DotsVertical = 'DotsVertical',
  CellphoneLink = 'CellphoneLink',
  AccountOutline = 'AccountOutline'
}

export enum ThemeColorEnum {
  Primary = 'primary',
  Warning = 'warning',
  Secondary = 'secondary',
  Error = 'error',
  Info = 'info',
  Success = 'success'
}

export enum ChaarvyIconFontSize {
  xs = '1rem',
  sm = '1.25rem',
  md = '1.5rem',
  lg = '1.75rem',
  xl = '2rem',
  xxl = '2.25rem'
}
